Repository microsoft/vscode-mssql, pull requests merged in 2024-10, with the labels that each got.

#18201 Removing additional buttons in table designer toolbar.
  localization/l10n/bundle.l10n.json
  src/reactviews/pages/TableDesigner/designerPageRibbon.tsx
Labels: Port Request

#18208 Porting "smattering of Azure browse bug fixes" (#18197)
  localization/l10n/bundle.l10n.json
  localization/xliff/vscode-mssql.xlf
  src/reactviews/common/locConstants.ts
  src/reactviews/common/utils.ts
  src/reactviews/media/azure-inverse.svg
  src/reactviews/media/azure.svg
  src/reactviews/pages/ConnectionDialog/azureBrowsePage.tsx
  src/reactviews/pages/ConnectionDialog/connectionPageContainer.tsx
  src/reactviews/pages/ExecutionPlan/queryPlanSetup.ts
Labels: Port Request

#18205 Porting Not collapsing all properties by default (#18202)
  localization/l10n/bundle.l10n.json
  localization/xliff/vscode-mssql.xlf
  src/reactviews/pages/TableDesigner/designerPropertiesPane.tsx
Labels: Port Request

#18221 Porting hid execution plan button under rich feature flag (#18219) and Query Plan Bugs (#18215)
  package.json
  src/models/sqlOutputContentProvider.ts
  src/reactviews/pages/ExecutionPlan/executionPlanGraph.tsx
  src/reactviews/pages/ExecutionPlan/executionPlanPage.tsx
  src/reactviews/pages/ExecutionPlan/findNodes.tsx
Labels: Port Request

#18227 Port: bump STS to bring in a few fixes #18224
  src/configurations/config.json
Labels: Port Request

#18238 Port Fix a few Query Result bugs: (#18234)
  localization/xliff/vscode-mssql.xlf
  media/revealQueryResult.svg
  package.json
  package.nls.json
  src/constants/constants.ts
  src/controllers/mainController.ts
  src/controllers/reactWebviewViewController.ts
  src/models/sqlOutputContentProvider.ts
  src/queryResult/queryResultWebViewController.ts
  src/reactviews/pages/QueryResult/queryResultPane.tsx
  src/reactviews/pages/QueryResult/table/interfaces.ts
  src/sharedInterfaces/queryResult.ts
Labels: Port Request

#18236 Port Add result grid context menu (#18206)
  localization/l10n/bundle.l10n.json
  localization/xliff/vscode-mssql.xlf
  src/controllers/queryRunner.ts
  src/models/sqlOutputContentProvider.ts
  src/queryResult/queryResultWebViewController.ts
  src/reactviews/common/locConstants.ts
  src/reactviews/common/vscodeWebviewProvider.tsx
  src/reactviews/pages/QueryResult/queryResultPane.tsx
  src/reactviews/pages/QueryResult/resultGrid.tsx
  src/reactviews/pages/QueryResult/table/plugins/contextMenu.css
  src/reactviews/pages/QueryResult/table/plugins/contextMenu.plugin.ts
  src/reactviews/pages/QueryResult/table/plugins/headerFilter.plugin.ts
  src/reactviews/pages/QueryResult/table/table.ts
  src/reactviews/pages/QueryResult/table/utils.ts
  src/sharedInterfaces/telemetry.ts
Labels: Port Request

#18228 Porting Improving first-run prompt flow (#18222)
  localization/l10n/bundle.l10n.json
  localization/xliff/vscode-mssql.xlf
  src/constants/locConstants.ts
  src/controllers/mainController.ts
Labels: Port Request

#18265 Porting Fix query plan flickering bug (#18258)
  src/reactviews/pages/QueryResult/queryResultPane.tsx
Labels: Port Request

#18266 Porting updated table designer publish dialog (#18259)
  localization/l10n/bundle.l10n.json
  localization/xliff/vscode-mssql.xlf
  src/reactviews/common/locConstants.ts
  src/reactviews/pages/TableDesigner/designerChangesPreviewButton.tsx
Labels: Port Request

#18272 Port Add min size & fix resize behavior (#18271)
  src/reactviews/pages/QueryResult/queryResultPane.tsx
Labels: Port Request, Pri: 0

#18268 Porting adding telemetry points to connection dialog (#18260)
  src/connectionconfig/connectionDialogWebviewController.ts
  src/sharedInterfaces/telemetry.ts
Labels: Port Request, Pri: 2

#18273 Porting survey telemetry fix (#18270)
  src/nps/userSurvey.ts
  src/reactviews/pages/UserSurvey/userSurveyPage.tsx
  src/sharedInterfaces/userSurvey.ts
Labels: Port Request, Pri: 2

#18286 Port Move onDidChangeActiveTextEditor event registration behind feature flag #18283
  src/controllers/mainController.ts
  src/queryResult/queryResultWebViewController.ts
Labels: Port Request
